### ISSUE TITLE
Configuring kafka fails to write ca-file

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-appliance_console#168]
```
Message Server Parameters:

Enter the Message Server Hostname or IP address: |localhost.localdomain| 
Enter the Message Keystore Username: |admin| 
Enter the Message Keystore Password: 
Configure a new persistent disk volume? (Y/N): 
Please enter "yes" or "no".
Configure a new persistent disk volume? (Y/N): N

Message Server Configuration:
Message Server Details:
    Message Server Hostname: localhost.localdomain
  Message Keystore Username: admin

Proceed? (Y/N): Y
Checking connectivity to localhost.localdomain ... 
Succeeded.
Create Jaas Config
Create Client Properties
Create Logs Directory
Configure Firewall
Configure Keystore

Generating a RSA private key
............................................................................................+++++
..................................+++++
writing new private key to '/opt/kafka/config/keystore/ca-key'
140400744777536:error:0907E06F:PEM routines:do_pk8pkey:read key:crypto/pem/pem_pk8.c:83:

Failed to Configure the Message Server- openssl exit code: 1 error was: Generating a RSA private key
............................................................................................+++++
..................................+++++
writing new private key to '/opt/kafka/config/keystore/ca-key'
140400744777536:error:0907E06F:PEM routines:do_pk8pkey:read key:crypto/pem/pem_pk8.c:83:

Message Server configuration failed!

Press any key to continue.
```

**Comment by bdunne** [comment]
Is this fixed by https://github.com/ManageIQ/manageiq-appliance_console/pull/170 ?

**Comment by agrare** [comment]
No this was actually a different error, without the directory this would fail with `req: Can't open "/opt/kafka/config/keystore/ca-key" for writing, No such file or directory`

I hit this after creating the directory and it fails with `140400744777536:error:0907E06F:PEM routines:do_pk8pkey:read key:crypto/pem/pem_pk8.c:83:`

Still don't know how to reproduce it yet, I wanted to capture it in an issue so we wouldn't lose it.

**Comment by Fryguy** [comment]
@agrare Is this still a thing with kafka 3.2?

**Comment by agrare** [comment]
Yes I was able to configure kafka with a locally built 3.2 rpm
```
Proceed with Configuration? (Y/N): Y

Message Server Parameters:

Enter the Message Server Hostname or IP address: |manageiq.rb.nj.grare.com| 
Enter the Message Keystore Username: |admin| 
Enter the Message Keystore Password: *******
Configure a new persistent disk volume? (Y/N): N

Message Server Configuration:
Message Server Details:
    Message Server Hostname: manageiq.rb.nj.grare.com
  Message Keystore Username: admin

Proceed? (Y/N): Y
Checking connectivity to manageiq.rb.nj.grare.com ... 
Succeeded.
Create Jaas Config
Create Client Properties
Create Logs Directory
Configure Firewall
Configure Keystore
Create Server Properties
Configure Messaging Yaml
Configure Messaging Type
Starting zookeeper and configure it to start on reboots ...
Starting kafka and configure it to start on reboots ...
Restart evmserverd if it is running...

Message Server configured successfully.

Press any key to continue.
```

Once we have the kafka 3.2 rpm as part of the upstream appliance image we can close this.

**Comment by bdunne** [comment]
Is this closed by https://github.com/ManageIQ/manageiq-rpm_build/pull/288 ?

**Comment by agrare** [comment]
I did not hit this when setting up kafka 3.2.  Do we have the latest kafka rpm built?

**Comment by bdunne** [comment]
Master appliances have `kafka-3.2.0-1` installed.
